---
title: "Code comparisons"
date: "`r Sys.Date()`"
output: 
rmarkdown::html_vignette:
css: custom.css 
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



## 1. read in the data

:::::::::::::: {.columns}
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}
devtools::install("/Users/rof011/symportalfunctions")
library(symportalfunctions)
library(tidyverse)

sym_folder="/Users/rof011/Symbiodinium/20210805T112901" # set the main folder for all functions

seqs <- extract_seqs_long(sym_folder, type="absolute", threshold = 0) # get sequences
its2.seq2 <- extract_its2_profile(sym_folder) # get ITS2 profiles
its2.seqs <- extract_its2_profile_seqs(sym_folder) # get ITS2 profiles
its2.names <- extract_its2_names(sym_folder) # get ITS2 profile names
colour.seqs <- extract_plot_colors(sym_folder) # get plot colors from symportal folder, no need to every subsample
metadata <- extract_metadata(sym_folder) # get plot colors from symportal folder, no need to every subsample

```

:::
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}
library(tidyverse)
library(vegan)
library(ape)
library(ggtree)
library(janitor)
library(RJSONIO)
library(data.table)

profiles.import <- read.delim("/Users/rof011/symbiodinium/20210805T112901/its2_type_profiles/9_brian-full-data_20210805T112901.profiles.relative.abund_and_meta.txt", check.names=FALSE, header=F)
its2.type.profile <- profiles.import %>% row_to_names(row_number = 7) %>% rename("sample_name" = 2) %>% select(-1) %>%filter(!sample_name== "")
its2.type.profile <- its2.type.profile %>% pivot_longer(-sample_name) %>% filter(value>0) %>% arrange(sample_name) %>% filter(!sample_name== "") %>% select(-value)
its2.type.profile <- its2.type.profile %>% pivot_wider(names_from=name, values_from=name) %>% unite("strings", 2:65, na.rm = TRUE, sep="=")  %>% separate(strings, paste0("ITS2.profile.",1:5), sep="=")


colour.seqs <- RJSONIO::fromJSON("/Users/rof011/symbiodinium/20210805T112901/html/color_dict_post_med.json")

plot.sequences.names <- read.delim("/Users/rof011/symbiodinium/20210805T112901/post_med_seqs/9_brian-full-data_20210805T112901.seqs.relative.abund_and_meta.txt", check.names=FALSE)

# load data for profile ID
profiles.import <- read.delim("/Users/rof011/symbiodinium/20210805T112901//its2_type_profiles/9_brian-full-data_20210805T112901.profiles.relative.abund_and_meta.txt", check.names=FALSE, header=F)
its2.type.profile <- profiles.import %>% row_to_names(row_number = 7) %>% rename("sample_name" = 2) %>% select(-1) %>%filter(!sample_name== "")
its2.type.profile <- its2.type.profile %>% pivot_longer(-sample_name) %>% filter(value>0) %>% arrange(sample_name) %>% filter(!sample_name== "") %>% select(-value)
its2.type.profile <- its2.type.profile %>% pivot_wider(names_from=name, values_from=name) %>% unite("strings", 2:65, na.rm = TRUE, sep="=")  %>% separate(strings, paste0("ITS2.profile.",1:5), sep="=")

its2.type.names <- profiles.import %>% row_to_names(row_number = 1) %>% rename("sample_name" = 2) %>% select(-1) %>%filter(!sample_name== "")
its2.type.names <- its2.type.names %>% pivot_longer(-sample_name) %>% filter(value>0) %>% arrange(sample_name) %>% filter(!sample_name== "") %>% select(-value)
its2.type.names <- its2.type.names %>% pivot_wider(names_from=name, values_from=name) %>% unite("strings", 2:65, na.rm = TRUE, sep="=")  %>% separate(strings, paste0("ITS2.profile.",1:5), sep="=")
its2.type.names <- its2.type.names %>% unite("UID", 2:6, na.rm = TRUE, sep="*")

# relevel ITS profiles to match seqnames from postmeds. Do this higher up if needed next time o the main profiles.relative.abund_and_meta.txt
splitlist <- bind_cols(its2.type.profile$sample_name,
                       rbindlist(lapply(strsplit(its2.type.profile$ITS2.profile.1 , split="(-)|(/)", fixed=FALSE), function(x) data.table(t(x))),fill = TRUE),
                       rbindlist(lapply(strsplit(its2.type.profile$ITS2.profile.2 , split="(-)|(/)", fixed=FALSE), function(x) data.table(t(x))),fill = TRUE),
                       rbindlist(lapply(strsplit(its2.type.profile$ITS2.profile.3 , split="(-)|(/)", fixed=FALSE), function(x) data.table(t(x))),fill = TRUE),
                       rbindlist(lapply(strsplit(its2.type.profile$ITS2.profile.4 , split="(-)|(/)", fixed=FALSE), function(x) data.table(t(x))),fill = TRUE),
                       rbindlist(lapply(strsplit(its2.type.profile$ITS2.profile.5 , split="(-)|(/)", fixed=FALSE), function(x) data.table(t(x))),fill = TRUE)) %>% rename(sample_name=1) %>%
  mutate_all(funs(str_replace(., "4624", "4624_C"))) %>%
  mutate_all(funs(str_replace(., "5025", "5024_D"))) %>%
  mutate_all(funs(str_replace(., "4582", "4582_C"))) %>%
  mutate_all(funs(str_replace(., "5223", "5223_D"))) %>%
  mutate_all(funs(str_replace(., "5049", "5049_C"))) %>%
  mutate_all(funs(str_replace(., "3125(?!_)", "3125_C"))) %>%
  mutate_all(funs(str_replace(., "3232", "3232_C"))) %>%
  mutate_all(funs(str_replace(., "4626", "4626_C"))) %>%
  mutate_all(funs(str_replace(., "4562", "4562_C"))) %>%
  mutate_all(funs(str_replace(., "4715", "4715_D"))) %>%
  mutate_all(funs(str_replace(., "3428", "3428_C"))) %>%
  mutate_all(funs(str_replace(., "3158", "3158_C"))) %>%
  mutate_all(funs(str_replace(., "4726", "4726_C"))) %>%
  mutate_all(funs(str_replace(., "4561", "4561_C"))) %>%
  mutate_all(funs(str_replace(., "3126", "3126_C"))) %>%
  mutate_all(funs(str_replace(., "4727", "4727_C"))) %>%
  mutate_all(funs(str_replace(., "4563", "4563_C"))) %>%
  mutate_all(funs(str_replace(., "4493", "4493_D"))) %>%
  mutate_all(funs(str_replace(., "4716", "4716_D"))) %>%
  mutate_all(funs(str_replace(., "3134(?!_)", "3134_C"))) %>%
  mutate_all(funs(str_replace(., "5033", "5033_D"))) %>%
  mutate_all(funs(str_replace(., "5019", "5019_D"))) %>%
  mutate_all(funs(str_replace(., "4440", "4440_C"))) %>%
  mutate_all(funs(str_replace(., "3149", "3149_C"))) %>%
  mutate_all(funs(str_replace(., "5261", "5261_C"))) %>%
  mutate_all(funs(str_replace(., "5286", "5286_A"))) %>%
  mutate_all(funs(str_replace(., "5386", "5386_D"))) %>%
  mutate_all(funs(str_replace(., "4610", "4610_D"))) %>%
  mutate_all(funs(str_replace(., "3660", "3660_C"))) %>%
  mutate_all(funs(str_replace(., "5531", "5531_A"))) %>%
  mutate_all(funs(str_replace(., "4247", "4247_C"))) %>%
  mutate_all(funs(str_replace(., "5387", "5387_D"))) %>%
  mutate_all(funs(str_replace(., "4453", "4453_C"))) %>%
  column_to_rownames(var="sample_name")

```
:::
::::::::::::::



#### 1A. PLOT BY SAMPLE NAME (all seqs) #####


:::::::::::::: {.columns}
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}

samplenumber = c("581", "356", "515", "198", "366")  # change sample numbers here and run code below

plot.seqs <- seqs %>% filter(sample.ID %in% samplenumber)
its2 <- its2.names %>% filter(sample_name %in% samplenumber) # get matching UID for the sample.ID

# plot
ggplot() + theme_bw() +  scale_fill_manual(values = colour.seqs) + xlab("") + ylab("") +
  geom_bar(data=plot.seqs, aes(fill=seq.ID, y=abundance, x=sample.ID), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  geom_text(data=its2, aes(x=sample_name, y=1.04, label=UID), angle=90) +
  theme(legend.position = "right", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

:::
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}


samplenumber = c("581", "356", "515", "198", "366")  # change sample numbers here and run code below

legendposition="right" # none, bottom, top, left, right

plot.sequences <- read.delim("/Users/rof011/symbiodinium/20210805T112901/post_med_seqs/9_brian-full-data_20210805T112901.seqs.absolute.abund_and_meta.txt", check.names=FALSE) %>% select(2, 38:ncol(.)) %>% pivot_longer(-sample_name, names_to="seqtype") %>%  filter(value > 0)  %>%  filter(sample_name %in% samplenumber)
colour.seqs.subset <- colour.seqs %>% as.data.frame() %>% rownames_to_column() %>% rename(seq=1, colorhtml=2)  %>% filter(seq %in% plot.sequences$seqtype) %>% deframe()
its2.type.names.subset <- its2.type.names %>% filter(sample_name %in% plot.sequences$sample_name) %>% arrange(UID)
create_factor <- function(x, levels = its2.type.names.subset$sample_name){factor(x, levels)}
plot.sequences <- plot.sequences %>% mutate_at("sample_name", create_factor)

ggplot() + theme_bw() + geom_bar(data=plot.sequences, aes(fill=seqtype, y=value, x=sample_name), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = legendposition, axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs.subset) +
  geom_text(data=its2.type.names.subset, aes(x=sample_name, y=1.1, label=UID), angle=90)

```
:::
::::::::::::::




#### 2B. PLOT BY SAMPLE NAME (all seqs) #####


:::::::::::::: {.columns}
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}


samplenumber = c("581", "356", "515", "198", "366")  # change sample numbers here and run code below

plot.seqs <- seqs %>% filter(sample.ID %in% samplenumber) # i) extract sequences and filter
its2.seqs.subset <- its2.seqs %>% filter(sample.ID %in% samplenumber) # ii) extract main ITS and filter
plot.seqs.subset <- plot.seqs %>% filter(seq.ID %in% its2.seqs.subset$seq.ID) # iii) filter the plot sequences to only include the main ITS2 seqs
its2 <- its2.names %>%  filter(sample_name %in% samplenumber) # make Y axis labels

ggplot() + theme_bw() + geom_bar(data=plot.seqs.subset, aes(fill=seq.ID, y=abundance, x=sample.ID), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs) +
  geom_text(data=its2, aes(x=sample_name, y=1.1, label=UID), angle=90)

```

:::
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}

samplenumber = c("581", "356", "515", "198", "366")  # change sample numbers here and run code below
legendposition="bottom" # none, bottom, top, left, right


plot.sequences.samples <- read.delim("/Users/rof011/symbiodinium/20210805T112901/post_med_seqs/9_brian-full-data_20210805T112901.seqs.absolute.abund_and_meta.txt", check.names=FALSE) %>% select(2, 38:ncol(.)) %>% pivot_longer(-sample_name, names_to="seqtype") %>%  filter(value > 0)   %>% filter(sample_name %in% samplenumber)
splitlist.sub <- splitlist %>% filter(rownames(.) %in% plot.sequences.samples$sample_name) %>% pivot_longer(cols = everything()) %>% na.omit() %>% unique()
plot.sequences <- plot.sequences.samples %>% filter(seqtype %in% splitlist.sub$value)
colour.seqs.subset <- colour.seqs %>% as.data.frame() %>% rownames_to_column() %>% rename(seq=1, colorhtml=2)  %>% filter(seq %in% plot.sequences$seqtype) %>% deframe()
its2.type.names.subset <- its2.type.names %>% filter(sample_name %in% plot.sequences$sample_name)

ggplot() + theme_bw() + geom_bar(data=plot.sequences, aes(fill=seqtype, y=value, x=sample_name), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = legendposition, axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs.subset) +
  geom_text(data=its2.type.names.subset, aes(x=sample_name, y=1.1, label=UID), angle=90)

```
:::
::::::::::::::






#### 3A. PLOT BY GENUS NAME (all seqs) ####


:::::::::::::: {.columns}
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}


genus = "Seriatopora"
genus_seqs <- metadata |> filter(host_genus==genus) %>% pull(sample_name) %>% as.character()


plot.sequences.genus <- seqs %>% filter(sample.ID %in% genus_seqs)
its2 <- its2.names %>% filter(sample_name %in% plot.sequences.genus$sample.ID) # make Y axis labels

ggplot() + theme_bw() + geom_bar(data=plot.sequences.genus, aes(fill=seq.ID, y=abundance, x=sample.ID), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs)

```

:::
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}

genus = "Seriatopora" # change genus here and run code below
legendposition="none" # none, bottom, top, left, right
#levels(as.factor(plot.sequences.names$host_genus)) # check genera

plot.sequences <- read.delim("/Users/rof011/symbiodinium/20210805T112901/post_med_seqs/9_brian-full-data_20210805T112901.seqs.absolute.abund_and_meta.txt", check.names=FALSE) %>% filter(host_genus==genus) %>% select(2, 38:ncol(.)) %>% pivot_longer(-sample_name, names_to="seqtype") %>%  filter(value > 0)
#plot.sequences <- plot.sequences %>% arrange(factor(sample_name, levels = its.order.samples$sample_name))
colour.seqs.subset <- colour.seqs %>% as.data.frame() %>% rownames_to_column() %>% rename(seq=1, colorhtml=2)  %>% filter(seq %in% plot.sequences$seqtype) %>% deframe()
its2.type.names.subset <- its2.type.names %>% filter(sample_name %in% plot.sequences$sample_name) %>% arrange(UID)
create_factor <- function(x, levels = its2.type.names.subset$sample_name){factor(x, levels)}
plot.sequences <- plot.sequences %>% mutate_at("sample_name", create_factor)

ggplot() + theme_bw() + geom_bar(data=plot.sequences, aes(fill=seqtype, y=value, x=sample_name), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = legendposition, axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs.subset) +
  geom_text(data=its2.type.names.subset, aes(x=sample_name, y=1.1, label=UID), angle=90)

```
:::
::::::::::::::




#### 3B. PLOT BY SAMPLE NAME (all seqs) #####


:::::::::::::: {.columns}
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}

genus = "Seriatopora" # change genus here and run code below


plot.seqs <- seqs %>% filter(sample.ID %in% genus_seqs) # i) extract sequences and filter
its2.seqs.subset <- its2.seqs %>% filter(sample.ID %in% genus_seqs) # ii) extract main ITS and filter
plot.seqs.subset <- plot.seqs %>% filter(seq.ID %in% its2.seqs.subset$seq.ID) # iii) filter the plot sequences to only include the main ITS2 seqs
its2 <- its2.names %>% filter(sample_name %in% genus_seqs) # make Y axis labels

ggplot() + theme_bw() + geom_bar(data=plot.seqs.subset, aes(fill=seq.ID, y=abundance, x=sample.ID), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs) +
  geom_text(data=its2, aes(x=sample_name, y=1.1, label=UID), angle=90)


```

:::
::: {.column width="50%"}
```{r warning=FALSE,message=FALSE}

genus = "Seriatopora" # change genus here and run code below
legendposition="bottom" # none, bottom, top, left, right
levels(as.factor(plot.sequences.names$host_genus)) # check genera

plot.sequences <- read.delim("/Users/rof011/symbiodinium/20210805T112901/post_med_seqs/9_brian-full-data_20210805T112901.seqs.absolute.abund_and_meta.txt", check.names=FALSE) %>% filter(host_genus==genus) %>% select(2, 38:ncol(.)) %>% pivot_longer(-sample_name, names_to="seqtype") %>%  filter(value > 0)
splitlist.sub <- splitlist %>% filter(rownames(.) %in% plot.sequences$sample_name) %>% pivot_longer(cols = everything()) %>% na.omit() %>% unique()
plot.sequences <- plot.sequences %>% filter(seqtype %in% splitlist.sub$value)
colour.seqs.subset <- colour.seqs %>% as.data.frame() %>% rownames_to_column() %>% rename(seq=1, colorhtml=2)  %>% filter(seq %in% plot.sequences$seqtype) %>% deframe()
its2.type.names.subset <- its2.type.names %>% filter(sample_name %in% plot.sequences$sample_name) %>% arrange(UID)
create_factor <- function(x, levels = its2.type.names.subset$sample_name){factor(x, levels)}
plot.sequences <- plot.sequences %>% mutate_at("sample_name", create_factor)


ggplot() + theme_bw() + geom_bar(data=plot.sequences, aes(fill=seqtype, y=value, x=factor(sample_name)), color="black", position = position_fill(reverse = TRUE), stat="identity") +
  theme(legend.position = legendposition, axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_fill_manual(values = colour.seqs.subset) +
  geom_text(data=its2.type.names.subset, aes(x=sample_name, y=1.1, label=UID), angle=90)

```
:::
::::::::::::::
