---
title: "<b>seq*sample<b>"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r setup, include=FALSE}
library(symportalfunctions)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(plotly)
library(flexdashboard)
library(shiny)


select_folder <- "/Users/rof011/symbiodinium/20220919T102058_esampayo"
plot_data <- extract_seqs_long(select_folder, type="absolute")
colour.seqs <- extract_plot_colors(select_folder)
its2.type.names <- extract_its2_names(select_folder)
```


Sidebar {.sidebar}
-----------------

```{r}

tags$style(HTML("
  .navbar-header .navbar-brand {
    font-size: 36px;  
  .sidebar {
    background-color: #f7f7f7;  
    padding: 20px;              
    border-right: 1px solid #e1e1e1; 
  }
  .shiny-input-container {
    margin-bottom: 40px;       
  }
  label {
    font-size: 20px;             
    font-weight: bold;         
    color: #555;               
    border-bottom: 1px solid #e1e1e1;     
  }
  
    #absoluteBtn {
        background-color: red;
        padding: 10px 15px;
        margin-left: 10px;  /* Spacing to the right of each button */

    }
    #relativeBtn {
        background-color: blue;
        padding: 10px 15px;
        margin-right: 10px;  /* Spacing to the right of each button */

    }
  .shiny-notification {
    font-size: 30px;  
  }

"))

div(
  actionButton("relativeBtn", "Relative"),
  actionButton("absoluteBtn", "Absolute"),
 style = "display: inline-block;"
 
)


div(
tags$h3("Select folder")
)

textInput("folderInput", "Specify base Symportal folder:", value = "/Users/rof011/symbiodinium/20220919T102058_esampayo")


div(
tags$h3("Set threshold")
)

numericInput("minAbundance", "Lower cutoff for seq abundance:", value = 0, min = 0)


div(
tags$h3("Filter by seqID")
)
selectInput("seqID", "Select seq.IDs from list", choices = c("ALL", unique(plot_data$seq.ID)), selected = "ALL", multiple = TRUE)

textInput("seqIDPattern", "Include seq.IDs (comma separated):", value = "")

div(
tags$h3("Filter by Sample")
)

selectInput("sample.ID", "Select sample.IDs from list", choices = c("ALL", unique(plot_data$sample.ID)), selected = "ALL", multiple = TRUE)

textInput("excludeSampleIDPatterns", "Exclude sample.IDs (comma seperated)", value = "")

div(
tags$h3("Save Plot")
)

textInput("filenameInput", "Filename:", value = "my_plot.png")


div(style = "display: inline-block; width: 40%;", 
    textInput("plotWidth", "Width:", value = "10")
)

div(style = "display: inline-block; width: 40%;", 
   textInput("plotHeight", "Height:", value = "6")
)

  
  

textInput("saveFolderInput", "Set folder path:", value = "/Users/rof011/symportalfunctions")
#textInput("saveFolderInput", "Set folder path:", value = "/path/to/your/default/folder")
actionButton("savePlotBtn", "Save Plot")








```



Column
---------------------

### Interactive Plot

```{r}

data_reactive <- reactive({
  req(input$folderInput) # makes sure folderInput is available and non-null
  
  plot_data <- extract_seqs_long(input$folderInput, type="absolute")
  colour.seqs <- extract_plot_colors(input$folderInput)
  its2.type.names <- extract_its2_names(input$folderInput)
  
  list(plot_data = plot_data, colour.seqs = colour.seqs, its2.type.names = its2.type.names)
})

reactivePlot <- reactive({
  
  # Your data processing code
  
  filtered_data <- plot_data 

  if ("ALL" %in% input$seqID) {
    filtered_data <- plot_data
  } else {
    filtered_data <- plot_data %>% filter(seq.ID %in% input$seqID)
  }

   if (nchar(input$minAbundance) > 0) {
      filtered_data <- filtered_data %>% filter(abundance > input$minAbundance) 
   }
  
  # Pattern match for seqID
  if (nchar(input$seqIDPattern) > 0) {
    patterns <- unlist(strsplit(input$seqIDPattern, ",\\s*"))
    pattern_matches_list <- purrr::map(patterns, ~grepl(.x, plot_data$seq.ID))
    combined_matches <- purrr::reduce(pattern_matches_list, `|`)
    pattern_filtered_data <- plot_data %>% filter(combined_matches)
    filtered_data <- dplyr::bind_rows(filtered_data, pattern_filtered_data)
  }

  # Excluding based on sample.ID
  if (nchar(input$excludeSampleIDPatterns) > 0) {
    patterns <- unlist(strsplit(input$excludeSampleIDPatterns, ",\\s*"))
    pattern_matches_list <- purrr::map(patterns, ~grepl(.x, filtered_data$sample.ID))
    combined_matches <- purrr::reduce(pattern_matches_list, `|`)
    filtered_data <- filtered_data %>% filter(!combined_matches)
  }

  filtered_data$seq.ID <- reorder(filtered_data$seq.ID, filtered_data$abundance)
  filtered_data$seq.ID <- factor(filtered_data$seq.ID, levels=rev(levels(filtered_data$seq.ID)))
  
  p <- ggplot() + theme_bw()

  if (abundanceType() == "Relative") {
    p <- p + geom_bar(data=filtered_data, aes(fill=seq.ID, y=abundance, x=sample.ID, group=abundance), 
                      color="black", linewidth=0.1, position = position_fill(reverse = TRUE),
                      show.legend=FALSE, stat="identity") +  scale_y_reverse()
  } else {
    p <- p + geom_bar(data=filtered_data, aes(fill=seq.ID, y=abundance, x=sample.ID, group=abundance), 
                      color="black", linewidth=0.1, show.legend=FALSE, stat="identity")
  }

  p <- p + scale_fill_manual(values = data_reactive()$colour.seqs) + 
    theme(legend.position = "bottom", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  
        
  return(p)
})

###
abundanceType <- reactiveVal("Relative") # default value
###

observeEvent(input$relativeBtn, {
  abundanceType("Relative")
})

observeEvent(input$absoluteBtn, {
  abundanceType("Absolute")
})

observeEvent(input$savePlotBtn, {
  
  #showNotification("Save button clicked!", type = "message") # Just for debugging
  
  # Folder path and file name from user input
  folder_path <- input$saveFolderInput
  file_name <- input$filenameInput
  
  # Ensure path ends with a / if it doesn't
  if(substr(folder_path, nchar(folder_path), nchar(folder_path)) != "/") {
    folder_path <- paste0(folder_path, "/")
  }
  
  full_path <- paste0(folder_path, file_name)  # Full path to save the plot
  
  plotH <- as.numeric(input$plotHeight)
  plotW <- as.numeric(input$plotWidth)
  
  
  p <- reactivePlot()  # Get the ggplot object

    tryCatch({
    ggsave(filename = full_path, plot = p, width = plotW, height = plotH)
    showNotification("Plot saved successfully!", type = "message")
  }, error = function(e) {
    showNotification(paste("An error occurred with the following warning:", e$message, "check the file directory and image type (.jpg, .pdf, .png) and width/height are correctly specified"), type = "error")
  })
  
  
})



output$plotUI <- renderPlotly({
  p <- reactivePlot()  # Access the reactive ggplot object
  ggplotly(p)
})


plotlyOutput("plotUI")

```
